### ISSUE TITLE
Install error on Debian

### ISSUE THREAD

**Issue by zzxzshiyf** [bro/pysubnettree#6]
run `python2.7 setup.py install`
got error: `c++: error: unrecognized command line option '-fstack-protector-strong'`

`error: command 'c++' failed with exit status 1`

i'm not familiar with C++,so can you give some adivce?

g++ version
`g++ (Debian 4.7.2-5) 4.7.2`

**Comment by jsiwek** [comment]
A guess is that some mismatch in your environment is causing that flag to be added (I don't find "-fstack-protector-strong" anywhere in the pysubnettree sources).  Is it set in CFLAGS or CXXFLAGS in your environment (check output of `env` command) ?

Or do you happen to use or have custom compiler or python versions on your system?  E.g. if python was built with a newer compiler version that did support -fstack-protector-strong, but it's now using an older compiler here, that might be a reason.

Trying this might be a way to override compile flags:

`BASECFLAGS="" OPT="" CFLAGS="" CXXFLAGS="" python2.7 setup.py install`

Another idea would be to check the output of:

`python2.7 -c "import sysconfig; print sysconfig.get_config_vars()"`

and see if -fstack-protector-strong shows up anywhere, then try manually overriding it by putting your own code in setup.py.

**Comment by zzxzshiyf** [comment]
Thanks,i just upgraded my gcc version to 4.8 and then solved this problem.Thanks again for your reply.
