### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by yijui** [bro/pysubnettree#7]
Is PySubnetTree thread-safe?

**Comment by jsiwek** [comment]
The short answer should be "yes".

The long answer depends on what you mean by thread-safe.  From what I understand of CPython's Global Interpreter Lock, use of pysubnettree as a library or SubnetTree objects created by it are implicitly going to be safe in the context of Python threads.  But notwithstanding the GIL (i.e. in case you were use a Python implementation without a GIL), pysubnettree as a C/C++ library looks thread-safe in the context of running other C/C++ code concurrently w/ a few conditions:

1. You don't compile/use the code contained within PATRICIA_DEBUG preprocessor blocks of the code.
2. You use SubnetTree objects like a map, not a set -- the later is implemented by just inserting a key and value where the value is statically allocated (so doing concurrent insert/remove operations could be a problem).  It would be trivial to patch out the re-use of this statically allocated dummy value.
3. It's up to the user to prevent concurrent access to a given SubnetTree object.
